# Generated by Django 5.1.2 on 2024-10-26 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialDish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('rating', models.IntegerField(default=5)),
                ('image', models.ImageField(upload_to='special_dishes/')),
            ],
        ),
    ]
