# Generated by Django 5.1.2 on 2024-11-08 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='special_dishes',
            field=models.ManyToManyField(blank=True, related_name='menu_items', to='restaurant.specialdish'),
        ),
    ]
