# Generated by Django 5.1.2 on 2024-11-10 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0013_alter_userprofile_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='user_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='restaurant.usercomment'),
        ),
    ]
